config/routes.rb
Rails.application.routes.draw do
  resources :money, only: %i[ index create destroy ]
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
    get '/users/sign_out', to: 'users/sessions#destroy'
    root "users/sessions#new"
  end
  resources :wallets, only: %i[ create show destroy ]
  resources :shops, except: %i[ new show ]
  resources :carts, only: %i[ create destroy ] do
    get 'add_item', on: :member
    get 'buy_item', on: :member
  end
  resources :cart_items, only: %i[ create update destroy]
  resources :items, except: %i[ new show ]
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  has_many :items, through: :cart_items
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[ destroy ]

  def add_item
    @cart = Cart.find_or_create_by(user_id: current_user.id)
    @cart_items = @cart.cart_items.where(bought: false)
    @shops = Shop.all
    @items = Item.all
    wallet = Wallet.find_or_create_by(user_id: current_user.id)
  end

  def buy_item
    @cart = Cart.find(params[:id])
    @cart_items = @cart.cart_items.where(bought: false)
    @cart_items.map do |cart_item|
      cart_item[:bought] = true
      cart_item.save
    end
    redirect_to add_item_cart_path(@cart.id)
  end

  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: "Cart was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def set_cart
      @cart = Cart.find(params[:id])
    end

    def cart_params
      params.require(:cart).permit(:user_id)
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/add_item.html.erb
<h1>Select Item Into Cart</h1>

<div class="d-flex flex-row">
  <%= render partial: 'items/index',  locals: {item: @items, cart_items: @cart_items} %>
  <div style="padding-left: 20px; border-left: solid 2px gray">
    <h3>Cart list</h3>
    <table>
      <thead>
        <tr>
          <th>Shop</th>
          <th>Name</th>
          <th>Price</th>
          <th>Stock</th>
          <th>quantity</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody id="cart_item_list">
        <% if @cart_items != nil %>
          <% @cart_items.each do |cart_item| %>
            <tr>
              <td><%= cart_item.item.shop.name %></td>
              <td><%= cart_item.item.name %></td>
              <td><%= cart_item.item.price %></td>
              <td><%= cart_item.item.stock %></td>
              <%= form_with(model: @cart_items, local: true, url: cart_item_path, method: :patch) do |form| %>
                <td><%= form.number_field :quantity, id: "quantity_form#{cart_item}", style: "width: 40px; height: 23px", class: "quantity_form", value: cart_item.quantity %>個</td>
                <td><%= form.submit "数量変更", id: "add_item_button#{cart_item}", class: "add_item_button" %></td>
                <%= form.hidden_field :id, value: cart_item.id %>
              <% end %>
              <td><%= link_to 'Destroy', cart_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
    <%= link_to '購入確定', buy_item_cart_path(id: @cart.id), data: { confirm: 'Are you sure?' }, class:"btn btn-info" %>
  </div>
</div>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Shop</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= cart.user_id %></td>
        <td><%= cart.shop_id %></td>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>