config/routes.rb
Rails.application.routes.draw do
  resources :money, only: %i[ index create destroy ]
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
    get '/users/sign_out', to: 'users/sessions#destroy'
    root "users/sessions#new"
  end
  resources :wallets, only: %i[ create show destroy ]
  resources :shops, except: %i[ new show ]
  resources :carts, only: %i[ create destroy ] do
    get 'add_item', on: :member
    get 'buy_item', on: :member
  end
  resources :cart_items, only: %i[ create update destroy]
  resources :items, except: %i[ new show ]
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :shop
  has_many :cart_items, dependent: :destroy

  with_options presence: true do
    validates :name
    validates :price
    validates :stock
    validates :comment
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ edit update destroy ]

  def index
    @items = Item.all
  end

  def edit
    @shops = Shop.all
  end

  def create
    @item = Item.new(item_params)
    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: "Item was successfully created." }
        format.json { render partial: 'items/item', status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to shops_path, notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to shops_path, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:name, :price, :stock, :comment, :shop_id)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: @item, local: true) do |form| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% @item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :stock %>
    <%= form.number_field :stock %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_field :comment %>
  </div>

  <div class="field">
    <%= form.label :shop_id %>
    <%= form.select :shop_id, @shops.all.map {|shop| ["#{shop.name}", shop.id]}, { prompt: '選択してください', "data-value" => "" }, id: "item_shop_form"%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/_index.html.erb
<div style="margin-right: 20px;">
  <h3>Item list</h3>

  <table>
    <thead>
      <tr>
        <%= content_tag :th, "date" if controller_name == "shops"%>
        <th>Shop</th>
        <th>Name</th>
        <th>Price</th>
        <th>Stock</th>
        <th>Comment</th>
        <% if controller == "carts" %>
          <th>quantity</th>
        <% end %>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody id="item_list">
      <% @items.each do |item| %>
        <tr>
          <%= content_tag :td, l(item.created_at, format: :long) if controller_name == "shops"%>
          <td><%= item.shop.name %></td>
          <td><%= item.name %></td>
          <td><%= item.price %></td>
          <td><%= item.stock %></td>
          <td><%= item.comment %></td>
          <% if controller_name == "carts" %>
            <%= form_with(model: @cart_items, local: true, url: cart_items_path) do |form| %>
              <td><%= form.number_field :quantity, id: "quantity_form#{item}", style: "width: 40px; height: 23px", class: "quantity_form" %>個</td>
              <td><%= form.submit "カートに追加", id: "add_item_button#{item}", class: "add_item_button" %></td>
              <%= form.hidden_field :cart_id, value: @cart.id %>
              <%= form.hidden_field :item_id, value: item.id %>
            <% end %>
          <% else %>
            <td> | <%= link_to 'Edit', edit_item_path(item) %> | </td>
            <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', shop: @item %>

<%= link_to 'Back', shops_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Stock</th>
      <th>Comment</th>
      <th>Shop</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.price %></td>
        <td><%= item.stock %></td>
        <td><%= item.comment %></td>
        <td><%= item.shop_id %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>