config/routes.rb
Rails.application.routes.draw do
  resources :money, only: %i[ index create destroy ]
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
    get '/users/sign_out', to: 'users/sessions#destroy'
    root "users/sessions#new"
  end
  resources :wallets, only: %i[ create show destroy ]
  resources :shops, except: %i[ new show ]
  resources :carts, only: %i[ create destroy ] do
    get 'add_item', on: :member
    get 'buy_item', on: :member
  end
  resources :cart_items, only: %i[ create update destroy]
  resources :items, except: %i[ new show ]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShoppingAppTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-info">
      <a class="navbar-brand" href="#">shopping_app</a>
      <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="ナビゲーションの切替">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav text-white">
          <% if user_signed_in? %>
            <span class="pl-3 pr-5 text-white text-left">user : <%= current_user.name %></span>
            <%= link_to "profile_edit", edit_user_registration_path(current_user.id), class: "text-white px-3" %>
            <%= link_to "shop", shops_path, class: "text-white px-3" %>
            <%= link_to "cart", add_item_cart_path(current_user.cart.id), class: "text-white px-3" %>
            <%= link_to "wallet", wallet_path(current_user.wallet.id), class: "text-white px-3" if controller != "shop" %>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "text-white px-3" %>
          <% else %>
            <%= link_to "新規登録", new_user_registration_path, class: "text-white px-3" %>
            <%= link_to "ログイン", new_user_session_path, class: "text-white px-3" %>
          <% end %>
        </div>
      </div>
    </nav>
    <%= yield %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script>
    <%= javascript_pack_tag 'moneyList_vue' %>
  </body>
</html>